### ISSUE TITLE
canPopout: Tooltip does not disappear when widget is popped out

### ISSUE THREAD

**Issue by cfranklyn** [iTwin/appui#279] opened 2023-04-18 15:18 UTC
**Describe the bug**
If I pop out my widget into another window, then minimize the main window (**important**), the iTwin-React tooltip does not disappear when I move the mouse away from the item that initiates its appearance.

**To Reproduce**

1. Create a widget with a Button and a Tooltip, set canPopout to "true"
2. Popout the widget
3. If you hover over the Button, the Tooltip appears and disappears as it should
4. Minimize the main browser window (i.e. the one that you didn't pop out)
5. Hover over the Button, Tooltip appears
6. Move the mouse away from the Button, the Tooltip remains even though it should disappear

**Expected behavior**
The Tooltip should disappear when you move the mouse away from the Button

**Screenshots**
![image](https://user-images.githubusercontent.com/92109722/232822038-81947b57-fc1a-41b6-abb3-f28bc246e1b2.png)

(the mouse is not over the button in this image)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser Chrome, also reproduced it in the appUI Electron sample
- Version 112.0.5615.121 (Official Build) (64-bit)
- iTwin.js AppUI Version: Reproduced in the appUI test app
- iTwin.js Version [e.g. 3.6.2]

**Additional context**

**Comment by mayank99** [comment] 2023-04-18 18:14
I am having a bit of trouble reproducing it in that codesandbox link. On Chrome macOS, the dialog is partially off screen, so I cannot even hover the button.  On Firefox macOS, the dialog is fine but the tooltip doesn't even appear when hovering the button.

**Comment by elephantcatdog** [comment] 2023-04-18 19:05
I was able to reproduce it in the sandbox (using Chrome), but there's lots of weird stuff happening.

https://user-images.githubusercontent.com/37936169/232878441-cc9ccc3c-cf21-4f6d-97ce-a9ed9cd613c4.mp4

1. Is popup supposed to open a new tab?
2. Once in the new tab, the popup is partially off screen.
3. Going back to the original tab and then to the popup tab, the dialog is in the correct place.
4. Hovering over the button, the tooltip is stuck.

https://user-images.githubusercontent.com/37936169/232878635-22b9131f-25bd-4aec-92dc-c4679f106514.mp4

5. I pulled the tab with the popup out of the same window, and then tooltip worked okay.
6. I minimized the original window, and then tooltip got stuck again.

**Comment by raplemie** [comment] 2023-04-18 19:13
Ok, I get these issue as well but the dialog get repositionned as soon as I resize the window, I used the code in https://github.com/iTwin/iTwinUI/pull/1174 so it would be simple, I thought it would help to have a known starting point.

In which playground do you usually put the code shown in the linked PR ?

**Comment by elephantcatdog** [comment] 2023-04-18 19:29
There's a few files in our codebase at iTwinUI/playgrounds called App.tsx that we can use to test things. It looks like Mayank was using iTwinUI/playgrounds/vite/src/App.tsx in that PR.

**Comment by elephantcatdog** [comment] 2023-04-19 15:49
Thanks for the new sandbox.

**Comment by mayank99** [comment] 2023-04-20 14:02
If this is because of some browser behavior, then I don't think we can do anything about it.

I was looking inside tippy's codebase and I found some lines that [specifically listen to window blur events](https://github.com/atomiks/tippyjs/blob/master/src/bindGlobalEventListeners.ts#L42-L58), but it could be unrelated. We are also starting work on our next major release very soon, and plan to replace Tippy with floating-ui, so this issue might just go away?

In either case, it seems like a very uncommon and minor issue, plus the proper behavior is returned when the window is restored. So I would say it doesn't need to be prioritized.

Open to other suggestions as well.

**Comment by cfranklyn** [comment] 2023-04-20 14:07
For what it's worth, I agree, I don't think it will bother users very much. I mostly just wanted to make the teams aware of it. I'll wait for the upgrade and see if the issue is still present.

**Comment by raplemie** [comment] 2023-04-20 14:10
In that case, can you create an issue in iTwinUI and I'll close this one (since it depends on their update cycle)

**Comment by mayank99** [comment] 2023-04-20 14:13
Now tracking in https://github.com/iTwin/iTwinUI/issues/1218

**Comment by raplemie** [comment] 2023-04-20 14:14
Thanks, will close this issue here then.

**Closed by raplemie** 2023-04-20 14:14 UTC
Labels: appui, iTwinUi
