### ISSUE TITLE
Can set widget to panel side that is not allowed if moving off existing panel

### ISSUE THREAD

**Issue by joehenry9498** [iTwin/appui#584] opened 2023-11-13 19:48 UTC
**Describe the bug**
Setting the `allowedPanels` of widget restricts what sides the widget can be docked to. This property is respected when docking a floating widget, but it is not always respected when docking an already docked panel widget. This issue is exemplified in the following video. The allowedPanels is set to just the left and right side, but the widget can be docked on top and bottom as well, if moving from an existing panel.
[AllowedPanelsBugExample.webm](https://github.com/iTwin/appui/assets/70602409/c1aee794-4057-4d61-bb79-efd12458e511)
![Screenshot 2023-11-13 143844](https://github.com/iTwin/appui/assets/70602409/609daa1d-a170-4da2-a959-57e747643786)

**To Reproduce**
Set `allowedPanels` of widget to above restrictions and try docking the widget both from floating and from docking.

**Expected behavior**
Widget only docks to sides it is allowed to regardless if it's already docked on a panel.

**Comment by KaroAug** [comment] 2024-01-15 08:18
The issue is fixed in [#594](https://github.com/iTwin/appui/pull/594)

**Closed by KaroAug** 2024-01-15 08:18 UTC
Labels: bug, react
