### ISSUE TITLE
Evaluate exporting functionality from itwin that is currently being used

### ISSUE THREAD

**Issue by Rock2000** [iTwin/appui#422] opened 2023-07-21 13:17 UTC
Civil code (and Pineapple code which Civil relies on) have a few cases where they import something that is not exported. We should evaluate if these can be exported officially, or if these apps should change their code. We're trying to support iTwin Studio and this is not allowed in that platform.

The following is a list of these cases:

1) In the civil-frontend package (src\components\TreeNodeWithChildrenRenderer.tsx) the following imports are used:
    import { ImageRenderer } from "@itwin/components-react/lib/cjs/components-react/common/ImageRenderer";
    import { TreeComponentTestId } from "@itwin/components-react/lib/cjs/components-react/tree/TreeComponentTestId";
    (There is also a similar import of TreeNodeContent, but it looks like that has now been exported)
2) In Pineapple's @bentley/itwin-common/src/component/colorpickerpopover/ColorPickerPopover.tsx there is:
    import { Popover } from "@itwin/itwinui-react/cjs/core/utils";
3) In Pineapple's @bentley/itwin-2d-widget/src/widget/sheet-viewer/SheetViewerToolbar.tsx:
    import {ToolbarItemsChangedArgs, ToolbarItemsManager} from "@itwin/appui-react/lib/cjs/appui-react/toolbar/ToolbarItemsManager";

**Comment by raplemie** [comment] 2023-07-21 15:16
1 is a duplicate of #419, and the requirement are discussed there.
2 is iTwinUi, not AppUI, feel free to file an issue there.
3 Can you describe the usecase for using this? I see that we have 2 hooks that are public and uses this class as an argument, so it might be an oversight that it is not public, I'll check in more depts what this actually does. (as even the current description of `ToolbarItemsManager` is wrong.

**Comment by raplemie** [comment] 2023-07-24 13:58
Ok, if an issue already exists for 1 and 3 then'll close this one and continue on the ones that existed prior.

**Closed by raplemie** 2023-07-24 13:58 UTC
