### ISSUE TITLE
Console error message shows memory leak

### ISSUE THREAD

**Issue by arome** [iTwin/appui#976] opened 2024-08-15 16:20 UTC
### Describe the bug

When running booster in development, right after launching the app and being presented with the iModel Selection screen, I see this error appearing in the console.
<img width="550" alt="image" src="https://github.com/user-attachments/assets/a10d8320-ae14-4cc5-801c-8c7cbe22ada2">
A similar error then appears again after selecting an iModel 
<img width="537" alt="image" src="https://github.com/user-attachments/assets/8b0f8168-0d88-41ac-bbb7-d1a5d3e0862a">

### To Reproduce

1. Run the booster app from VS Code. 
2. After the app launches, open the chrome devTools (Mac: Command + Option + I, Windows/Linux: F12 or Control + Shift + I)
3. You'll see in the console the error message appearing

### Expected Behavior

I'm expecting the console to not have any errors thrown.

### Desktop (please complete the applicable information)

- OS: MacOS
- iTwin Studio for Developers: Version 1.0.60 (1.0.60.0)
- iTwin.js AppUI Version:   @itwin/appui-react": "4.12.0"

**Comment by ignas-k** [comment] 2024-08-19 14:07
Could you provide the specific iModel which you open to reproduce the second warning? I can reproduce the first one just fine but I don't get the second one.

**Comment by ignas-k** [comment] 2024-08-20 13:15
I looked into the issue. Seems like the warning is coming from studio's code and it is thrown by iTwinUI. I could not reproduce the second warning message but I got some another similar warning (component from another iTwin repository). However, the question is: is this issue urgent for you? This is not even an error but a warning and everythings seems to work just fine. Besides that this warning is removed in React 18 (and studio are already planning on upgrading) because it produces mostly false positives and the workarounds make the code worse (admitted by React developers). Link from the React documentation about this topic: https://react.dev/blog/2022/03/08/react-18-upgrade-guide#react (third entry, also has a link to the PR with examples and justification). Would you mind waiting for React 18 upgrade or do you need this fixed now?

**Comment by mayank99** [comment] 2024-08-20 15:04
I think this issue is safe to close, because it happens only in React 17 and only during development when using [Strict Mode](https://react.dev/reference/react/StrictMode). We could add workarounds, but since this warning doesn't happen in the latest React version and it does not cause any real issues, it's not worth adding extra code.

In Strict Mode, React unmounts/remounts the components, which results in [iTwinUI's `setState` call](https://github.com/iTwin/iTwinUI/blob/1d3e2e5e5bd453ea03127c4d9d9b960a0047b5ac/packages/itwinui-react/src/utils/components/ShadowRoot.tsx#L113) executing after the component is unmounted. As [explained](https://redirect.github.com/facebook/react/pull/22114) by React core team member, this is a false positive — `setState` called on an unmounted component gets simply ignored. There is no memory leak because we aren't setting up any subscriptions.

**Comment by arome** [comment] 2024-08-20 16:02
thanks for looking into it. It's definitely not a blocker and not urgent for me. I was just pointing it out in case this was causing memory leak in the app and since its a false positive and the error is expected to be fixed with a React update then lets wait for that.

**Closed** 2024-08-20 16:12 UTC
Labels: bug
