### ISSUE TITLE
Browser locks up when TreeSelectionManager gets a shift-click for a large number of tree nodes (>200)

### ISSUE THREAD

**Issue by wilmaier** [iTwin/appui#462] opened 2023-08-23 20:28 UTC
**Describe the bug**
The application freezes and the tab needs to be refreshed.
Selecting everything by parent node works without issues. This could be related to lazy loading because if I scroll down very slowly and let every node get loaded before selecting the last element then the app does not freeze.

**To Reproduce**

1. Open IModel that would have a few hundred elements
2. Type 'a' into the search widget field
3. Expand node with a large amount of elements
4. Select the first one and scroll down to the bottom and shift+click the last element.

**Expected behavior**
Clicking on the parent node causes all of the child nodes to be added to selection set.
Using shift click to select all child nodes should work the same.

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser: Chrome 
- Version 116.0.5845.110 (Official Build) (64-bit)
- iTwin.js AppUI Version 4.4.0
- iTwin.js Version 4.1.0

**Comment by grigasp** [comment] 2023-08-24 06:57
Adding repro steps that are easier to understand:

1. Go to [presentation rules editor](https://presentationruleseditor.bentley.com/open-imodel?iTwinId=b27dc251-0e53-4a36-9a38-182fc309be07&iModelId=f30566da-8fdf-4cba-b09a-fd39f5397ae6#editor/N4IgTgrgNgpgzjALiAXCYAdAdgAhxkASwBMCV8QAlaeJARgIBps8DJY4ycBtFvHTLn6twNACoBPAA4wuBSgHsFiAHILi8Jn2EE4MgMaEAZoX0BDRIQVZOqHtuECHjinpj7JMuSACSNxGZY+jBqGnAA8kYAygbGpgDCUGZwCLbMQi4i+kkpmnaCmY66+gAWMAC2Zipm5bJ2BABChHDxCmB16YU6INnJcNW1tuS8GV0iAKKwtViIBM6ZALrzwgC+nV0EZu0ACgpQEuVtUiWmXIiQMOuFBADmYAoQUg0SiX1cRmZQCFeZt-ePzwAMmYAEYwKDvT4IZY4FbzJajOFCBErEArIA).
2. Select the first node in the tree on the right.
3. Click on the scrollbar handle and quickly drag it to the bottom.
4. While holding the `Shift` key, click on one of the nodes.
5. Notice the frontend is hung.

![2023-08-24_09-51-50](https://github.com/iTwin/appui/assets/35135765/11914c96-19fb-477a-bb38-7f397881ecd9)

The problem is related to the tree requirement to load all intermediate nodes between the two selected ones.

**Comment by raplemie** [comment] 2023-09-01 14:45
Hi! A fix have been done, I'll let you know when it gets released.

**Comment by raplemie** [comment] 2023-09-06 18:13
Hi @wilmaier, a fix for this was released today in 4.5.0. Please try it out and let us know if this fixes your issue!

**Comment by wilmaier** [comment] 2023-09-06 19:07
Yes thanks. This fixes the issue.

**Comment by grigasp** [comment] 2023-09-07 05:56
@raplemie, I guess the issue should be closed?

**Comment by raplemie** [comment] 2023-09-07 15:18
Yes, thanks.

**Closed by raplemie** 2023-09-07 15:18 UTC
Labels: bug, presentation
