### ISSUE TITLE
Move from appui to iTwinUI `Dialog`

### ISSUE THREAD

**Issue by AntanasBuk** [iTwin/appui#363] opened 2023-06-14 14:19 UTC
This issue will need to be addressed when iTwinUI v3 comes out, that should introduce changes as well as fixes to its `Dialog` component. 

Moving from core-react to itwinui-react `Dialog` is necessary to standardize use of a single component. Both components have very similar functionality though only itwinui-react `Dialog` component follows iTwin UI standards.

```[tasklist]
### Components that will require changes (some breaking):
- [ ] `SampleModalDialog`
- [ ] `SampleModelessDialog`
- [ ] `AccuDrawDialog`
- [ ] `SaveFormatModalDialog`
- [ ] `MessageBox`
- [ ] `ContentDialog`
- [ ] `UiDataProvidedDialog`
- [ ] `ColorPickerDialog`
```

```[tasklist]
### Deprecating components in favor of using AppUI `Dialog`:
- [x] `Dialog`
- [x] `ModelessDialog`
- [x] `GlobalDialog`
```

There might be more components that need to change or be deprecated. Some components might need a complete overhaul.
There is also appui-layout-react `Dialog` component, so not sure what to do with it.

**Comment by AntanasBuk** [comment] 2023-06-15 13:10
Deprecations in https://github.com/iTwin/appui/pull/366

**Comment by mayank99** [comment] 2023-07-18 14:34
Hey @AntanasBuk, could you elaborate on this part?

> This issue will need to be addressed when iTwinUI v3 comes out, that should introduce changes as well as fixes to its Dialog component.

What changes/fixes from iTwinUI are you waiting for? afaik, the only thing we added is the `portal` prop in https://github.com/iTwin/iTwinUI/pull/1300.

**Comment by AntanasBuk** [comment] 2023-07-18 16:25
Hey @mayank99, I've already related and discussed all the issues with Greta Nausedaite a month back and she said that most of the issues were already fixed but were still waiting for v3 since they introduced breaking changes.

Regardless, since I often get prompted from iTwinUI team about these specific issues, I'll list them here:
1. When Dialog is resizable and **not** draggable, there is no minHeight set, so Dialog box can freely be resized with no regard to contents and leave them overboard. 
![image](https://github.com/iTwin/appui/assets/124153238/e15e64c0-1225-4f26-a848-f66b62fd5ce2)
2. When Dialog is resizable and **not** draggable, Dialog.ButtonBar does not stick to the bottom of the Dialog when being oversized. 
![image](https://github.com/iTwin/appui/assets/124153238/81eeb127-21eb-45b2-a1b8-e098d3c34dfa)
3. When Dialog is resizable and **not** draggable, resizing on either side moves the whole Dialog in very strange ways.
4. When Dialog is draggable, I observed a strange behavior where when it is dragged and closed it sometimes saves its previous position when being reopened. You can confirm this behavior even on your storybook for the Dialog component but it may take 20-40 tries of opening the Dialog, moving it, closing it and opening it again.
5. When the Dialog is draggable, the upper edges of the Dialog.TitleBar aren't rounded.
6. Dialog's "relativeTo" attribute should probably have and option for a "document" or something similar like the Modal component's "ownerDocument".
7. I saw that iTwinUI internally has alignment functionality for the Dialog, would be helpful if it was public.
8. iTwinUI storybook on Dialog lists props for Modal component (to me it is a bit strange that Modal and Dialog are separate components with different props).

In our case issues 1-3 (and maybe 4) are major blockers for moving to iTwinUI Dialog.
If anything needs further clarification, feel free to reach out :)

**Comment by mayank99** [comment] 2023-07-18 17:31
> 1. When Dialog is resizable and **not** draggable, there is no minHeight set, so Dialog box can freely be resized with no regard to contents and leave them overboard.
>
> 2. When Dialog is resizable and **not** draggable, Dialog.ButtonBar does not stick to the bottom of the Dialog when being oversized.

Looks like both of these were only fixed for draggable dialogs, not resizable (relevant PRs: https://github.com/iTwin/iTwinUI/pull/1046 and https://github.com/iTwin/iTwinUI/pull/1066). There is no bug currently tracked and not planned to be fixed in v3. We'll look into this and see if it can be fixed in v2.

> 3. When Dialog is resizable and **not** draggable, resizing on either side moves the whole Dialog in very strange ways.

I cannot reproduce this. Could you elaborate on this, perhaps with a video? I'll also wait for @gretanausedaite to respond if she knows anything about it.
 
> 4. When Dialog is draggable, I observed a strange behavior where when it is dragged and closed it sometimes saves its previous position when being reopened. You can confirm this behavior even on your storybook for the Dialog component but it may take 20-40 tries of opening the Dialog, moving it, closing it and opening it again.

This is indeed strange. We'll look into making this behavior consistent if it can be reproduced. In the meantime, if you want to ensure the position is reset, you can unmount the component (i.e. remove it from your tree).

> 5. When the Dialog is draggable, the upper edges of the Dialog.TitleBar aren't rounded.

There is no bug currently tracked and not planned to be fixed in v3. We'll look into this and see if it can be fixed in v2.

> 6. Dialog's "relativeTo" attribute should probably have and option for a "document" or something similar like the Modal component's "ownerDocument".

There might be a misunderstanding from your side as to how `relativeTo` works. All this prop does is toggle `position: fixed` vs `position: absolute`. It doesn't matter which document/window the dialog is rendered into. See description: https://github.com/iTwin/iTwinUI/blob/4cf2c6006803f2864681fbc15b4d52d0f97bcd1b/packages/itwinui-react/src/core/Dialog/DialogContext.tsx#L60-L68

> 7. I saw that iTwinUI internally has alignment functionality for the Dialog, would be helpful if it was public.

Assuming you're referring to `placement` near the corners. This was added recently in https://github.com/iTwin/iTwinUI/pull/1323 to be released in v3. We might be able to backport this to v2 (TBD).

> 8. iTwinUI storybook on Dialog lists props for Modal component (to me it is a bit strange that Modal and Dialog are separate components with different props).

The `Modal` component is a convenience wrapper built on top of `Dialog`, whereas `Dialog` gives you more control and flexibility over every single part. In AppUI's case, I assume `Dialog` is the one that is desired, so you can ignore `Modal`. We plan to explain the difference more clearly in our documentation website.

> In our case issues 1-3 (and maybe 4) are major blockers for moving to iTwinUI Dialog.

Thanks for the list! We'll work on getting these resolved soon to unblock you.

**Comment by AntanasBuk** [comment] 2023-07-19 08:46
Thank you for the feedback @mayank99 We'll keep track of the issues and deprecate our Dialog when the time comes. 

Regarding this issue:
> 3. When Dialog is resizable and **not** draggable, resizing on either side moves the whole Dialog in very strange ways.

I reproduced the bug on a sandbox though this time for both draggable and non-draggable Dialog resizing on the left side produced undesirable behavior. Resizing on the right side worked fine though.

![DialogResizeBug](https://github.com/iTwin/appui/assets/124153238/09ee88d2-b2f6-456b-aa32-bf14320be15f)

**Comment by mayank99** [comment] 2023-07-25 15:43
hey @AntanasBuk, of the above, **1**, **2**, **3** and **5** have been fixed in [`@itwin/itwinui-react@2.11.10`](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.11.10).

I could not reproduce **4**, but as I mentioned above, you can unmount the component to make the behavior consistent. all the others have been answered above as well.

hopefully this unblocks you :)

**Comment by AntanasBuk** [comment] 2023-07-25 16:55
Well that was fast 😮 I'll check with the team if everything is in order and start writing up a codemod for moving to iTwinUI's Dialog. Thanks for a quick response.

**Comment by AntanasBuk** [comment] 2023-07-27 12:21
Hey @mayank99 there is still one apparent issue with resizable (non-draggable) Dialog. Upon first resize the whole Dialog shifts to one side and changes how resize functionality works.
![DialogResizeBug](https://github.com/iTwin/appui/assets/124153238/92317cbd-4815-45d5-9dc1-d68055f162c6)
Personally I like how resizing the Dialog only shifts one side without affecting the opposite side (I believe this is the intended functionality cause this is how it works if the draggable Dialog).
I think the issue lies in the `transform` style prop being applied only after the first resize (as seen in the gif) since when the Dialog is also draggable the `transform` is set from the get go (it is probably set after the first render to preserve Dialogs position).

**Comment by mayank99** [comment] 2023-07-27 15:40
@AntanasBuk this should be fixed in [2.11.11](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.11.11), give it a try

**Comment by raplemie** [comment] 2023-08-15 18:55
@AntanasBuk , I just released 4.4.0 with the upgrade to 2.11.11, did you have anything else to do in this issue ?

**Comment by mayank99** [comment] 2023-08-15 19:17
> > 7. I saw that iTwinUI internally has alignment functionality for the Dialog, would be helpful if it was public.
> 
> Assuming you're referring to `placement` near the corners. This was added recently in [iTwin/iTwinUI#1323](https://github.com/iTwin/iTwinUI/pull/1323) to be released in v3. We might be able to backport this to v2 (TBD).

fyi this is also released in 2.12.x

**Comment by AntanasBuk** [comment] 2023-08-17 09:55
@raplemie the issue is mainly for deprecating certain Dialog components, until then it should probably be open

**Comment by AntanasBuk** [comment] 2023-08-17 09:57
@mayank99 I've tried 2.12.1 but our tests started throwing warnings, haven't investigated further and left it at 2.11.11

**Closed** 2024-06-20 09:33 UTC
Labels: iTwinUI, react

**Comment by ignas-k** [comment] 2024-06-20 09:38
All public components that use AppUI's `Dialog` have been changed to use iTwinUI's dialogs or have been deprecated.
