### ISSUE TITLE
clearHideIsolateEmphasizeElements icon doesnt clear up when the element's visibility is toggled from Models tree

### ISSUE THREAD

**Issue by muthubentley** [iTwin/appui#264] opened 2023-04-12 04:50 UTC
**Describe the bug**
clearHideIsolateEmphasizeElements icon doesnt clear up when the element's visibility is toggled from Models tree

**To Reproduce**
Issue can be reproduced in the below sandbox:
https://www.itwinjs.org/sandboxes/MuthuKalamani/ContextToolWithModelTree

1. Select and element and click "Hide Element" icon
![image](https://user-images.githubusercontent.com/107229931/231352329-2130167f-a7e7-45a6-8f11-cb3d7d6bdab8.png)
2. Confirm the element is hidden in viewer and tree. clearHideIsolateEmphasizeElements eye icon(encircled in red) is also displayed in the top toolbar
![image](https://user-images.githubusercontent.com/107229931/231352527-31403573-2a7b-4c9c-b7bb-31a2a9efa862.png)
3. Now press the eye icon in the tree to toggle the visibility of the element. Though all the elements are visible , clearHideIsolateEmphasizeElements eye icon doesnt clear up.
![image](https://user-images.githubusercontent.com/107229931/231352698-b0611bfa-583b-4332-965b-037f5806295b.png)

**Expected behavior**
When all elements are visible, clearHideIsolateEmphasizeElements eye icon should clear up from the viewer.

- Version:
- iTwin.js AppUI Version [3.7.1]
- iTwin.js tree-widget-react Version [e.g. 0.7.2]

**Comment by raplemie** [comment] 2023-04-12 15:26
This will be investigated for 4.1 release

**Comment by muthubentley** [comment] 2023-04-12 23:13
@raplemie  thanks. Can this be released before this month end?

**Comment by raplemie** [comment] 2023-04-13 12:56
We dont have a date for 4.1 yet. It may come to a patch version to 4.0 (so earlier than 4.1) but I cant promise a release date for now.

**Comment by muthubentley** [comment] 2023-07-14 02:55
@raplemie  @AntanasBuk  Its been a while since this issue was created. Can you please prioritize this issue?

**Comment by AntanasBuk** [comment] 2023-07-14 09:25
@muthubentley I remember looking into it a month back and found some other strange behaviors stemming from this issue so we will probably need to communicate what the intended behavior should look like (I'll compile a list later on).

**Comment by AntanasBuk** [comment] 2023-07-21 12:31
Update:

Ok, so the list of issues is as follows:
1. The original issue described above.
2. Hiding an element through the Model Tree does not make clearHideIsolateEmphasizeElements icon appear.
3. Hiding an element through the Model Tree (and in turn unselecting that element in the viewer) does not make hideElements icon disappear.

The problems with these issues are caused on our end by not adding listeners for hide/show elements events of the viewport and mostly only relying on buttons being clicked.

I've already managed to fix issues 1 and 3, so if nothing else comes up, I should be able to make a PR some time next week.

**Comment by AntanasBuk** [comment] 2023-07-21 14:07
Just found another problem, hiding elements via Hide Categories button from StandardContentToolsUiItemsProvider and then showing them again via Model Tree completely prevents that element category from being hidden again via Hide Categories button.
Guess this will not be a simple fix after all.

**Comment by muthubentley** [comment] 2023-07-24 07:22
> Just found another problem, hiding elements via Hide Categories button from StandardContentToolsUiItemsProvider and then showing them again via Model Tree completely prevents that element category from being hidden again via Hide Categories button. Guess this will not be a simple fix after all.

@AntanasBuk  Is this one relevant to current issue? This seems to be a different problem related to trees

**Comment by AntanasBuk** [comment] 2023-07-24 07:33
Its more of the same, we store element visibility override states based on appui events and ignore events from itwin-core. I am searching for a convenient way to check if any models and categories of elements visibility are being overriden (checking for overriden individual elements as described in your issue is a more simple case though and if you are in a hurry I'll definitely do a PR this week for that).

**Comment by muthubentley** [comment] 2023-07-24 07:37
@AntanasBuk  there is no hurry. Fukui also would like to have a stable version without impacts. Please take your time and analyze all the possible impacts.

**Comment by AntanasBuk** [comment] 2023-07-26 10:57
https://github.com/iTwin/appui/pull/425 

This PR fixes following issues and will be available with the next minor release:
> 1. The original issue described above.
> 2. Hiding an element through the Model Tree does not make clearHideIsolateEmphasizeElements icon appear.
> 3. Hiding an element through the Model Tree (and in turn unselecting that element in the viewer) does not make.

Issues related to overriding categories and models to the best of my knowledge would require running queries constantly and that would be less than ideal. AppUI team will need to decide how to best approach these issues.

On another note, @muthubentley please tell us if this solves the issues you were facing. We'll keep this issue open and wait for your feedback :)

**Comment by muthubentley** [comment] 2023-08-02 05:13
@AntanasBuk  can you please let me know the version in which this fix is available?

**Comment by AntanasBuk** [comment] 2023-08-02 08:32
@muthubentley the fix will be available with the next minor release (4.4.0). It should be available next week or at the end of this week.

**Comment by raplemie** [comment] 2023-08-15 18:41
Hi @muthubentley, the fix for this was released today in 4.4.0. Let us know if this fixes your issue!

**Comment by muthubentley** [comment] 2023-08-16 02:33
@AntanasBuk  @raplemie  Thanks for the fixes. Below three scenarios works well:

1. The original issue described above.
2. Hiding an element through the Model Tree does not make clearHideIsolateEmphasizeElements icon appear.
3. Hiding an element through the Model Tree (and in turn unselecting that element in the viewer) does not make hideElements icon disappear.

But when the category is hidden from Tree, eye icon doesnt show up. I will check with partner about the behavior. Based on their reply we can handle it as a separate issue. This issue can be closed.

**Closed** 2023-08-17 09:13 UTC
Labels: bug, appui
